name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user: KUSHRAJSINH
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg

      - name: Push Snake File to Output Branch
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake.svg output/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output
          git commit -m "Update Snake Animation" || echo "No changes to commit"
          git push origin HEAD:output
