name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: KUSHRAJSINH
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Snake Animation"
          branch: output
          file_pattern: "dist/github-contribution-grid-snake.svg"
          create_branch: true
